### ISSUE TITLE
OpenZeppelin 2.1.1 imported but not installed in readme 

### ISSUE THREAD

**Issue by officialnico** [oceanprotocol/vw-cli#1]
**Describe the bug**
OpenZeppelin 2.1.1 is imported in Simpletoken.sol
https://github.com/oceanprotocol/vw-cli/blob/d7a723a1476ef3d47f0c5d8da12b362847b8286f/contracts/Simpletoken.sol#L4

This is never installed.

SafeMath.sol 5.0.0^ is also in the contracts folder, so either we use SafeMath.sol in the contracts or we download the entire OpenZeppelin 2.1.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Download using the steps in readme
2. install python prerequisites
3. brownie install OpenZeppelin 4.0.0 
4. brownie compile
5. See error

**Error**
<img width="1440" alt="Screen Shot 2022-04-06 at 9 09 19 AM" src="https://user-images.githubusercontent.com/5944146/161982361-ce0089b5-35c0-486c-8516-601cda4a9d33.png">

**Expected behavior**
<img width="777" alt="Screen Shot 2022-04-06 at 9 16 53 AM" src="https://user-images.githubusercontent.com/5944146/161983500-203ed677-a3f1-4e7f-937e-2be75148b607.png">

**Comment by trentmc** [comment]
Thanks for the catch @officialnico ! Fixed. LMK if issues persist.
