### ISSUE TITLE
In vw wallet, ensure that tokens aren't lost if someone accidentally sends to it

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/vw-cli#11]
**Motivation**

Q/concern : what if someone accidentally sends erc20 tokens to vestingwallet.sol, assuming that the wallet could send them on using erc20 interface?

Could be a real problem. Eg OPF accidentally does it, or a DF partner. Could be Ms of tokens lost. That's why I've marked this issue as a bug.

**TODOs:**
- [ ] Support in .sol. Inspiration: [here's](https://github.com/oceanprotocol/df-py/blob/e57693cf21661db2eed1a3a33ae2aeb81e9c8be3/contracts/DFRewards.sol#L102) how the same problem was solved for DFRewards.sol, for [df-py#47](https://github.com/oceanprotocol/df-py/issues/47). 
- [ ] Support with .py unit test. Inspiration: [here's](https://github.com/oceanprotocol/df-py/blob/main/util/test/test_withdrawfunc.py) the unit tests for DFRewards.sol, for [df-py#47](https://github.com/oceanprotocol/df-py/issues/47).

(Note: this was originally in issue 10, but that issue weirdly had a PR for df-py linked to it, which always showed up in Zenhub board. Moved to this new issue so we don't keep seeing the PR.)

**Comment by idiom-bytes** [comment]
Let's have a short discussion around this so we can sort out the architecture.

**Comment by trentmc** [comment]
"Architecture" can be simple: it's philosophically similar to "gulp()" in Balancer v1. 
- If you call Balancer amm gulp(), the contract will move any funds at its address into its liquidity pool attribute.
- here, if you call vesting gulp(), the contract will move any funds at its address into the vesting wallet attribute. (OR: maybe it alreadg does this by the nature of its implementation? If yes, great! Either way, we will want to write a unit test to capture the target behavior)

**Comment by trentmc** [comment]
> The tokens & ETH sent to the contract are not lost but vested over time

Great! 

Then this issue's concern is nothing to be concerned about! :)

Nothing else to do.
