### ISSUE TITLE
Test exponential vw numbers against approx function and sign off

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/vw-cli#19]
### Problem:
Test and verify exponential vesting numbers are accurate

### DoD:
- [x] Numbers have been generated from contract sim
- [x] Sim numbers have been compared to the whitepaper/real numbers
- [x] Sim numbers have been compared on a long trajectory and have been verified
- [x] Sim emission tests have been signed off

**Comment by idiom-bytes** [comment]
This looked good to go. @trentmc can you sign off on this, or is there something else remaining on this step?

**Comment by trentmc** [comment]
Yes, I reviewed. Happy to sign off. I can close it.
