### ISSUE TITLE
Testnet vw & splitter contracts - Goerli

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/vw-cli#20]
### Problem:
We need to make sure that vw and splitter contracts are working as expected.
Verify they are working in a testnet (besides ganache, we likely won't test them dispensing e2e).
Test them as best as possible.

### Testing
- [x] Test requirements have been defined
- [x] Test basic dispense functions on a testnet
- [x] Validate any coverage that @alexcos20 raises up
- [x] Validate that df-py, address.json, and other systems are connected with it

### DoD:
- [x] Test coverage has been implemented and verified

**Comment by idiom-bytes** [comment]
If we deploy this onto testnet, we can start validating what parts of the apps are working and which ones aren't.

**Comment by trentmc** [comment]
Before we do a remote testnet:

Do we have really truly end-to-end tests on ganache?
