### ISSUE TITLE
Linear vesting might not properly vest. Test better, fix

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/vw-cli#7]
**Is your feature request related to a problem? Please describe.**
#5 reintroduced linear vesting.

But I haven't tested it thoroughly. It may have the issue of #1. 

**TODOs**

- [ ] Test more thoroughly
- [ ] Fix issues found. #2 describes some possible fixes.

**Comment by idiom-bytes** [comment]
I think we can close this? It sounds like we're not using linear vesting.

**Comment by trentmc** [comment]
We may not be using linear vesting directly. But our approximation of exponential may have the issue? Best to check it out. Cc @trizin
